//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillCourse.DataBaseStructure.serialize {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class SerializeSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static SerializeSetting defaultInstance = ((SerializeSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SerializeSetting())));
        
        public static SerializeSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/")]
        public string SerializationPath {
            get {
                return ((string)(this["SerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionCourse")]
        public string CourseCollectionSerializationPath {
            get {
                return ((string)(this["CourseCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionTask")]
        public string TaskCollectionSerializationPath {
            get {
                return ((string)(this["TaskCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionAnswerToTask")]
        public string AnswerToTaskCollectionSerializationPath {
            get {
                return ((string)(this["AnswerToTaskCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionCertificate")]
        public string CertificateCollectionSerializationPath {
            get {
                return ((string)(this["CertificateCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionSubscription")]
        public string SubscriptionCollectionSerializationPath {
            get {
                return ((string)(this["SubscriptionCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionUser")]
        public string UserCollectionSerializationPath {
            get {
                return ((string)(this["UserCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionStudent")]
        public string StudentCollectionSerializationPath {
            get {
                return ((string)(this["StudentCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./serializations/collectionTeather")]
        public string TeatherCollectionSerializationPath {
            get {
                return ((string)(this["TeatherCollectionSerializationPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./image/Users/")]
        public string UserImages {
            get {
                return ((string)(this["UserImages"]));
            }
            set {
                this["UserImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./image/Courses/")]
        public string CourseImage {
            get {
                return ((string)(this["CourseImage"]));
            }
            set {
                this["CourseImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./image/Users/default_v1.1.png")]
        public string UserImagesDefault {
            get {
                return ((string)(this["UserImagesDefault"]));
            }
            set {
                this["UserImagesDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./image/Courses/default_563x391.png")]
        public string CourseImageDefault {
            get {
                return ((string)(this["CourseImageDefault"]));
            }
            set {
                this["CourseImageDefault"] = value;
            }
        }
    }
}
